name: "Bandit"

on:
  push:
    branches:
      - master
    
  pull_request:
    branches:
      - master
  schedule:
    - cron: '36 7 * * 0'

jobs:
  Check:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Set up Python 3.10
      id: setup-python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install Bandit
      run: |
        pip install --upgrade bandit
    - name: Run Checks
      run: |
        bandit --recursive .