name: Release (PyPI)

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Set up Poetry
      uses: Gr1N/setup-poetry@v7
    - name: Cache Poetry
      id: cache-poetry
      uses: actions/cache@v2.1.7
      with:
        path: ~/.cache/pypoetry/virtualenvs
        key: ${{ runner.os }}-poetry-v2-${{ hashFiles('**/Pipfile.lock') }}
    - name: Install Poetry Dependencies
      if: steps.cache-poetry.outputs.cache-hit != 'true'
      run: |
        poetry install
    - name: Build + Upload Package to PyPI
      uses: JRubics/poetry-publish@v1.11
      with:
        pypi_token: ${{ secrets.PYPI_TOKEN }}
